[project]
name = "koi-net-graph-extension"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "koi-net>=2.1.0b1",
    "rid-lib>=3.3.0b1",
    "deepdiff>=9.0.0",
    "pyld>=3.0.0",
    "pyshacl>=0.31.0",
    "rdflib>=7.6.0",
]
